#!/usr/bin/env node
/**
 * Scans the images/ folder and generates gallery-data.js.
 * Run with: npm run build
 *
 * Photo titles come from the filename (e.g. "my-cool-app.jpg" -> "My Cool App").
 * To customize titles/descriptions/order, create images/captions.json:
 *   {
 *     "my-cool-app.jpg": { "title": "My Cool App", "description": "A thing I built." }
 *   }
 * You can also set the site title/subtitle in site.json (see below).
 */
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const IMAGES_DIR = path.join(ROOT, "images");
const OUT_FILE = path.join(ROOT, "gallery-data.js");

const IMAGE_EXTS = new Set([
  ".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif", ".svg",
]);

function prettify(filename) {
  const base = filename.replace(/\.[^.]+$/, "");
  return base
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function readJsonSafe(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return {};
  }
}

function main() {
  if (!fs.existsSync(IMAGES_DIR)) {
    fs.mkdirSync(IMAGES_DIR, { recursive: true });
  }

  const captions = readJsonSafe(path.join(IMAGES_DIR, "captions.json"));
  const site = readJsonSafe(path.join(ROOT, "site.json"));

  const files = fs
    .readdirSync(IMAGES_DIR)
    .filter((f) => IMAGE_EXTS.has(path.extname(f).toLowerCase()))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  const items = files.map((file) => {
    const meta = captions[file] || {};
    return {
      src: "images/" + encodeURIComponent(file),
      title: meta.title !== undefined ? meta.title : prettify(file),
      description: meta.description || "",
    };
  });

  const payload = {
    title: site.title || "",
    subtitle: site.subtitle || "",
    items,
  };

  const banner =
    "/* AUTO-GENERATED by build.js. Run `npm run build` after changing images/. */\n";
  fs.writeFileSync(
    OUT_FILE,
    banner + "window.GALLERY_DATA = " + JSON.stringify(payload, null, 2) + ";\n"
  );

  console.log(
    `Built gallery-data.js with ${items.length} image${items.length === 1 ? "" : "s"}.`
  );
  if (!items.length) {
    console.log("Tip: drop image files into the images/ folder, then run again.");
  }
}

main();
