/* AUTO-GENERATED by build.js. Run `npm run build` after changing images/. */
window.GALLERY_DATA = {
  "title": "My Projects",
  "subtitle": "A collection of things I've built.",
  "items": [
    {
      "src": "images/01-first-project.svg",
      "title": "Project One",
      "description": "Swap this placeholder for a real photo and edit this caption."
    },
    {
      "src": "images/02-second-project.svg",
      "title": "Project Two",
      "description": "Titles default to the filename if you delete this file."
    },
    {
      "src": "images/03-third-project.svg",
      "title": "Project Three",
      "description": "Optional — captions.json is not required."
    }
  ]
};
