/* AUTO-GENERATED by build.js. Run `npm run build` after changing images/. */
window.GALLERY_DATA = {
  "title": "My Projects",
  "subtitle": "A collection of some things I've built.",
  "items": [
    {
      "src": "images/1.png",
      "title": "",
      "description": ""
    },
    {
      "src": "images/2.png",
      "title": "",
      "description": ""
    },
    {
      "src": "images/3.png",
      "title": "",
      "description": ""
    },
    {
      "src": "images/4.png",
      "title": "",
      "description": ""
    },
    {
      "src": "images/5.png",
      "title": "",
      "description": ""
    },
    {
      "src": "images/6.png",
      "title": "",
      "description": ""
    }
  ]
};
